/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.inventrysystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author KIIT
 */
public class transaction extends javax.swing.JFrame {

    /**
     * Creates new form transaction
     */
    public transaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        jLabelClient = new javax.swing.JLabel();
        jLabelTransaction = new javax.swing.JLabel();
        jLabelInwardData = new javax.swing.JLabel();
        jLabelPrint = new javax.swing.JLabel();
        jLabelSearch = new javax.swing.JLabel();
        jLabelAS = new javax.swing.JLabel();
        jLabelRefrsh = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDeliiveryINfO = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelHeight = new javax.swing.JLabel();
        jLabelAmount = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelRemark = new javax.swing.JLabel();
        jTextFieldClientId = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldVechileNumber = new javax.swing.JTextField();
        jTextFieldDesc = new javax.swing.JTextField();
        jTextFieldLength = new javax.swing.JTextField();
        jTextFieldWeight = new javax.swing.JTextField();
        jTextFieldHeight = new javax.swing.JTextField();
        jTextFieldAmount = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldLocation = new javax.swing.JTextField();
        jTextFieldRemark = new javax.swing.JTextField();
        jDateChooserDeliv = new com.toedter.calendar.JDateChooser();
        jPanel10 = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory Transaction");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("     INVENTORY MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        jLabelHome.setBackground(new java.awt.Color(204, 204, 204));
        jLabelHome.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelHome.setText("               HOME");
        jLabelHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });

        jLabelClient.setBackground(new java.awt.Color(204, 204, 204));
        jLabelClient.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelClient.setText("              CLIENTS");
        jLabelClient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientMouseClicked(evt);
            }
        });

        jLabelTransaction.setBackground(new java.awt.Color(204, 204, 204));
        jLabelTransaction.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelTransaction.setText("         TRANSACTIONS");
        jLabelTransaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTransactionMouseClicked(evt);
            }
        });

        jLabelInwardData.setBackground(new java.awt.Color(204, 204, 204));
        jLabelInwardData.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelInwardData.setText("    INWARD DATA ITEMS");
        jLabelInwardData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPrint.setBackground(new java.awt.Color(204, 204, 204));
        jLabelPrint.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelPrint.setText("               PRINT");
        jLabelPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelSearch.setBackground(new java.awt.Color(204, 204, 204));
        jLabelSearch.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelSearch.setText("             SEARCH");
        jLabelSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelAS.setBackground(new java.awt.Color(204, 204, 204));
        jLabelAS.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelAS.setText("ANALYTICAL STASTISTICS");
        jLabelAS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelRefrsh.setBackground(new java.awt.Color(204, 204, 204));
        jLabelRefrsh.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelRefrsh.setText("             REFRESH");
        jLabelRefrsh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelLogout.setBackground(new java.awt.Color(204, 204, 204));
        jLabelLogout.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelLogout.setText("             LOGOUT");
        jLabelLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInwardData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRefrsh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 92, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelHome)
                .addGap(18, 18, 18)
                .addComponent(jLabelClient)
                .addGap(18, 18, 18)
                .addComponent(jLabelTransaction)
                .addGap(18, 18, 18)
                .addComponent(jLabelInwardData)
                .addGap(18, 18, 18)
                .addComponent(jLabelPrint)
                .addGap(18, 18, 18)
                .addComponent(jLabelSearch)
                .addGap(18, 18, 18)
                .addComponent(jLabelAS)
                .addGap(18, 18, 18)
                .addComponent(jLabelRefrsh)
                .addGap(18, 18, 18)
                .addComponent(jLabelLogout)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transaction:Delivery all items information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        jTableDeliiveryINfO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDeliiveryINfO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDeliiveryINfOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDeliiveryINfO);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delivery", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Client Id:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Client Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Vechile Number:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Description:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Delivery Date:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Length:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("weight:");

        jLabelHeight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHeight.setForeground(new java.awt.Color(0, 153, 153));
        jLabelHeight.setText("Height:");

        jLabelAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAmount.setForeground(new java.awt.Color(0, 153, 153));
        jLabelAmount.setText("Amount:");

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPrice.setForeground(new java.awt.Color(0, 153, 153));
        jLabelPrice.setText("Price:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Source Location");

        jLabelRemark.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRemark.setForeground(new java.awt.Color(0, 153, 153));
        jLabelRemark.setText("Remark");

        jTextFieldClientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClientIdActionPerformed(evt);
            }
        });
        jTextFieldClientId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldClientIdKeyReleased(evt);
            }
        });

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jTextFieldLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLengthActionPerformed(evt);
            }
        });

        jTextFieldAmount.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        jDateChooserDeliv.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDesc)
                    .addComponent(jTextFieldLocation)
                    .addComponent(jTextFieldClientId)
                    .addComponent(jTextFieldName)
                    .addComponent(jTextFieldVechileNumber)
                    .addComponent(jDateChooserDeliv, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAmount)
                    .addComponent(jLabelPrice)
                    .addComponent(jLabelRemark))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldHeight, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRemark, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldWeight)
                    .addComponent(jTextFieldLength, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldClientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHeight)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldVechileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAmount)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabelPrice)
                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserDeliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRemark)
                    .addComponent(jTextFieldRemark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(0, 255, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        jButtonClear.setBackground(new java.awt.Color(0, 255, 153));
        jButtonClear.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 51, 51));
        jButtonClear.setText("Clear/Reset");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonSave.setBackground(new java.awt.Color(0, 255, 153));
        jButtonSave.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(255, 51, 51));
        jButtonSave.setText("Save/Insert");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 255, 153));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Delete/Remove");

        jButton4.setBackground(new java.awt.Color(0, 255, 153));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 51, 51));
        jButton4.setText("Edit/Update");

        jButton5.setBackground(new java.awt.Color(0, 255, 153));
        jButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 51, 51));
        jButton5.setText("Print\n");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonClear)
                .addGap(46, 46, 46)
                .addComponent(jButtonSave)
                .addGap(45, 45, 45)
                .addComponent(jButton3)
                .addGap(52, 52, 52)
                .addComponent(jButton4)
                .addGap(50, 50, 50)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jLabelHomeMouseClicked

    private void jLabelClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientMouseClicked
        // TODO add your handling code here:
        this.dispose();
        clientInformation ci=new clientInformation();
        ci.setVisible(true);

    }//GEN-LAST:event_jLabelClientMouseClicked

    private void jLabelTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransactionMouseClicked

    }//GEN-LAST:event_jLabelTransactionMouseClicked

    private void jTextFieldClientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClientIdActionPerformed

    private void jTextFieldLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLengthActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldClientId.setText("");
        jTextFieldName.setText("");
        jTextFieldDesc.setText("");
        jTextFieldAmount.setText("");
        jTextFieldHeight.setText("");
        jTextFieldLength.setText("");
        jTextFieldLocation.setText("");
        jTextFieldVechileNumber.setText("");
        jTextFieldPrice.setText("");
        jTextFieldRemark.setText("");
        jTextFieldWeight.setText("");
        jDateChooserDeliv.setDate(null);
        
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        mysqlconnect myc=new mysqlconnect();
        PreparedStatement ps;
        
        
        Connection con=myc.getConnection();
        double amount=Double.parseDouble(jTextFieldAmount.getText());
        double rate=Double.parseDouble(jTextFieldPrice.getText());
        double delivery=amount*rate;
        double tot=0;
        double tot1=0;
        try{
            String query="select * from client_info where id='"+jTextFieldClientId.getText()+"'";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query);
            
            while(rs.next()){
                tot=rs.getDouble(1);
            }
            tot=tot+delivery;
            
            query="update client_info set total_delivery=? where id=?";
            ps=con.prepareStatement(query);
            ps.setDouble(1, tot);
            ps.setInt(2, Integer.parseInt(jTextFieldClientId.getText()));
            ps.executeUpdate();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Transaction save Button error" +e);
        }
        
        try{
            java.sql.Date date=new java.sql.Date(jDateChooserDeliv.getDate().getTime());
            amount=Double.parseDouble(jTextFieldAmount.getText());
            rate=Double.parseDouble(jTextFieldPrice.getText());
            
            double mul=amount*rate;
            String s=""+mul;          
            String sql="select total_paid_amount from client_info where id='"+jTextFieldClientId.getText()+"'";
            Statement st =con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                tot1=rs.getDouble(1);
            }
            double due=tot-tot1;
            String du=" "+due;
            String tot_delivery=""+tot;
            String ad="0";
            if(due>=0){
                String sql1="insert into delivery_table(id,name,truck_number,description,loading_place,delivery_date,lenghth,weight,height,amount,price,total_amount,due_amount,advance,reamrks,total_delivery) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
          ps=con.prepareStatement(sql1);    
                
                ps.setInt(1, Integer.parseInt(jTextFieldClientId.getText().toString()));
                ps.setString(2,jTextFieldName.getText());
                ps.setString(3,jTextFieldVechileNumber.getText());
                ps.setString(4, jTextFieldDesc.getText());
                ps.setString(5, jTextFieldLocation.getText());
                ps.setDate(6, date);
                ps.setDouble(7,Double.parseDouble(jTextFieldLength.getText().toString()));
                ps.setDouble(8,Double.parseDouble(jTextFieldWeight.getText().toString()));
               // ps.setDouble(9,Double.parseDouble(jTextFieldLength.getText().toString()));
                ps.setDouble(9,Double.parseDouble(jTextFieldHeight.getText().toString()));
                ps.setDouble(10,Double.parseDouble(jTextFieldAmount.getText().toString()));
                ps.setDouble(11,Double.parseDouble(jTextFieldPrice.getText().toString()));
                ps.setDouble(12,Double.parseDouble(s.toString()));
                 ps.setDouble(13, Double.parseDouble(du.toString()));
                 ps.setDouble(14, Double.parseDouble(ad.toString()));
                 ps.setString(15, jTextFieldRemark.getText());
                 ps.setDouble(16,Double.parseDouble(tot_delivery.toString()));
                
                 int i=ps.executeUpdate();
                 if(i>=1){
                     JOptionPane.showMessageDialog(null,jTextFieldName.getText()+ " Transaction record saved to database");
                 }else{
                      JOptionPane.showMessageDialog(null,jTextFieldName.getText()+ " Transaction record failed");
                 }
            }else{
                due=due*-1;
                ad=""+due;
                 String sql1="insert into delivery_table(id,name,truck_number,description,loading_place,delivery_date,lenghth,weight,height,amount,price,total_amount,due_amount,advance,reamrks,total_delivery) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";                ps=con.prepareStatement(sql1); 
                
                ps.setInt(1, Integer.parseInt(jTextFieldClientId.getText().toString()));
                ps.setString(2,jTextFieldName.getText());
                ps.setString(3,jTextFieldVechileNumber.getText());
                ps.setString(4, jTextFieldDesc.getText());
                ps.setString(5, jTextFieldLocation.getText());
                ps.setDate(6, date);
                ps.setDouble(7,Double.parseDouble(jTextFieldLength.getText().toString()));
                ps.setDouble(8,Double.parseDouble(jTextFieldWeight.getText().toString()));
               // ps.setDouble(9,Double.parseDouble(jTextFieldLength.getText().toString()));
                ps.setDouble(9,Double.parseDouble(jTextFieldHeight.getText().toString()));
                ps.setDouble(10,Double.parseDouble(jTextFieldAmount.getText().toString()));
                ps.setDouble(11,Double.parseDouble(jTextFieldPrice.getText().toString()));
                ps.setDouble(12,Double.parseDouble(s.toString()));
                
                ps.setDouble(13, Double.parseDouble(du.toString()));
                 ps.setDouble(14, Double.parseDouble(ad.toString()));
                 ps.setString(15, jTextFieldRemark.getText());
                 ps.setDouble(16,Double.parseDouble(tot_delivery.toString()));
                 
                 
                 int i=ps.executeUpdate();
                 if(i>=1){
                     JOptionPane.showMessageDialog(null,jTextFieldName+ "  else 2Transaction record saved to database");
                 }else{
                      JOptionPane.showMessageDialog(null,jTextFieldName+ "else 2 Transaction record failed");
                 }
                
            }  
           
            //String sql=
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Transaction error "+e);
        }
        finally{
            try{
               if(con!=null){
                   con.close();
                   System.out.println("Connection closed...");
               } 
            }catch(Exception e){
                Logger.getLogger(transaction.class.getName()).log(Level.SEVERE, null,e);
            }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldClientIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldClientIdKeyReleased
        // TODO add your handling code here:
        PreparedStatement ps;
        mysqlconnect myc=new mysqlconnect();
        Connection con=myc.getConnection();
        try{
            String cid=jTextFieldClientId.getText();
            System.out.println("Transaction class selected class is "+cid);
            String query="select name from client_info where id='"+cid+"'";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query);
            
            String name;
            double t_paid_amt,t_discount,t_delivey,cal;
            if(rs.next()==false){
                System.out.println("Transaction client id releases if block ");
                jTextFieldClientId.setText("");
            }else{
                name=rs.getString(1);
                jTextFieldName.setText(name);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Transaction client id key released"+ e);
        }finally{
            try{
                if(con!=null){
                    con.close();
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"transacton id show error"+ e);
            }
        }
    }//GEN-LAST:event_jTextFieldClientIdKeyReleased

    private void jTableDeliiveryINfOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDeliiveryINfOMouseClicked
        // TODO add your handling code here:
         PreparedStatement ps;
        mysqlconnect myc=new mysqlconnect();
        Connection con=myc.getConnection();
        ResultSet rs;
        try{
            int row=jTableDeliiveryINfO.getSelectedRow();
            String table_click=jTableDeliiveryINfO.getModel().getValueAt(row, 0).toString();
            String query="select * from delivery_table where id ='"+table_click+"'";
            ps=con.prepareStatement(query);
            rs=ps.executeQuery();
            if(rs.next()){
                jTextFieldClientId.setText(rs.getString("id"));
                jTextFieldName.setText(rs.getString("name"));
                jTextFieldDesc.setText(rs.getString("description"));
                jTextFieldVechileNumber.setText(rs.getString("truck_number"));
                jTextFieldLocation.setText(rs.getString("loading_place"));
                jTextFieldAmount.setText(rs.getString("amount"));
                jTextFieldLength.setText(rs.getString("lenghth"));
                jTextFieldHeight.setText(rs.getString("height"));
                jTextFieldWeight.setText(rs.getString("weight"));
                jTextFieldPrice.setText(rs.getString("price"));
                jTextFieldRemark.setText(rs.getString("reamrks"));
                rs.getString("total_amount");
                rs.getString("due_amount");
                rs.getString("advance");
                rs.getString("delivery_date");
                String sd=rs.getObject("date").toString();
                java.util.Date date=new SimpleDateFormat("yyyy-MM-dd").parse(sd);
                jDateChooserDeliv.setDate(date);
                  
            }
        }catch(Exception e){
              System.out.println("transaction error"+e);
             JOptionPane.showMessageDialog(null,"error"+ e);
        }
    }//GEN-LAST:event_jTableDeliiveryINfOMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonSave;
    private com.toedter.calendar.JDateChooser jDateChooserDeliv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAS;
    private javax.swing.JLabel jLabelAmount;
    private javax.swing.JLabel jLabelClient;
    private javax.swing.JLabel jLabelHeight;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelInwardData;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelPrint;
    private javax.swing.JLabel jLabelRefrsh;
    private javax.swing.JLabel jLabelRemark;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelTransaction;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDeliiveryINfO;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldClientId;
    private javax.swing.JTextField jTextFieldDesc;
    private javax.swing.JTextField jTextFieldHeight;
    private javax.swing.JTextField jTextFieldLength;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldRemark;
    private javax.swing.JTextField jTextFieldVechileNumber;
    private javax.swing.JTextField jTextFieldWeight;
    // End of variables declaration//GEN-END:variables
}
